avodha_demo/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demo_avodha_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

demo_avodha_app/urls.py
from django.urls import path

from . import views

app_name='myapp'
urlpatterns=[
    path('',views.demo,name='demo'),
    path('shop/<int:shop_id>',views.detail,name='detail'),
    path('add',views.add_product,name='add_product'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete')

]

demo_avodha_app/models.py
from django.db import models

# Create your models here.
class shop(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField()
    price=models.IntegerField()
    img=models.ImageField(upload_to="images")

demo_avodha_app/forms.py
from django import forms
from . models import shop

class ModeForm(forms.ModelForm):
    class Meta:
        model=shop
        fields=['name','desc','price','img']

demo_avodha_app/views.py
from django.shortcuts import render,redirect
from . forms import ModeForm

from .models import shop

# Create your views here.
def demo(request):
    obj=shop.objects.all()
    return render(request,"home.html",{'products':obj})

def detail(request,shop_id):
    product1=shop.objects.get(id=shop_id)
    return render(request,"details.html",{'prod':product1})

def add_product(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        price=request.POST.get('price')
        img=request.FILES['img']
        s=shop(name=name,desc=desc,price=price,img=img)
        s.save()
    return render(request,"add_product.html")

def update(request,id):
    obj=shop.objects.get(id=id)
    form = ModeForm(request.POST or None,request.FILES,instance=obj)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'obj':obj})

def delete(request,id):
    if request.method=='POST':
        obj=shop.objects.get(id=id)
        obj.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add_product.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="prod name" /><br />
  <input type="text" name="desc" placeholder="prod desc" /><br />
  <input type="text" name="price" placeholder="prod price" /><br />
  <input type="file" name="img" placeholder="prod img" /><br />
  <input type="submit" value="ADD" />
</form>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block content %} {% endblock %}
  </body>
</html>

templates/delete.html
<form method="post">
  {% csrf_token %} Are you sure to delete?
  <input type="submit" value="ok" />
</form>

templates/details.html
{% extends 'base.html' %} {% block content %}
<a href="{% url 'myapp:update' prod.id %}">update</a>
<a class="btn btn-warning" href="{% url 'myapp:delete' prod.id %}">Delete</a>

<h1>{{prod.desc}}</h1>
<img src="{{prod.img.url}}" alt="" style="height: 200px; width: 200px" />
{% endblock %}

templates/edit.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{form.as_p}} <input type="submit" value="Update" />
</form>

templates/home.html
{% extends 'base.html' %} {% block content %} {% for prod in products %}
<div style="display: flex">
  <a href="{% url 'myapp:detail' prod.id %}">{{prod.name}}=></a>
</div>
{% endfor %} {% endblock %}